services:

  db:
    image: postgres:17
    container_name: safebox-db
    environment:
      POSTGRES_DB: safebox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: safebox-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/safebox
      SPRING_DATASOURCE_USERNAME: safebox_app
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AES_SECRET: ${AES_SECRET}
    ports:
      - "8080:8080"

volumes:
  pgdata:
